on: push
name: build and publish

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: ghcr.io/rpgminecraftprogrammers/datagenerator:${{ github.REF_NAME }}
    steps:
      - name: Execute
        shell: bash
        working-directory: /app
        run: |
          java -jar /app/datagenerator.jar --base-remote "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" --base-ref $GITHUB_REF_NAME --dtd-remote "https://github.com/RPGMinecraftProgrammers/Vulpes-DTD.git" --dtd-ref $GITHUB_REF_NAME
